#ifndef CONFIG_H
#define CONFIG_H

// AoC2023 version 1.0.2023.1
// Autogenerated header file, do not modify!!
// Header file: config.h
// Last modified: 2023-12-02 16:52:11

namespace AoC
{
    namespace Metadata
    {
        static const char* version = "1.0.2023.1";
        static const char* author = "Marco Carosio";
        static const char* desc = "Advent of Code 2023";
        static const char* last_commit_date = "2023-12-01 17:34:41 +0100";
        static const char* last_commit_hash = "3f0c05d52498157f8a963d9d3a44a4b4b1ede7b1";
    }

    namespace Settings
    {
        static const char *input_directory = "/home/marco/repos/github/mcarosio80/AoC2023/input";
    }
} // AoC

#endif // CONFIG_H
