#ifndef CONFIG_H
#define CONFIG_H

// AoC2023 version 1.0.2023.1
// Autogenerated header file, do not modify!!
// Header file: config.h
// Last modified: 2023-12-01 17:16:49

namespace AoC
{
    namespace Metadata
    {
        static const char* version = "1.0.2023.1";
        static const char* author = "Marco Carosio";
        static const char* desc = "Advent of Code 2023";
        static const char* last_commit_date = "2023-12-01 09:03:12 +0100";
        static const char* last_commit_hash = "389b571b4874a8b65bd21f3e6eb9e36620577dba";
    }

    namespace Settings
    {
        static const char *input_directory = "/home/marco/repos/github/mcarosio80/AoC2023/input";
    }
} // AoC

#endif // CONFIG_H
