#ifndef CONFIG_H
#define CONFIG_H

// Advent of Code version 1.0.2023.1
// Autogenerated header file, do not modify!!
// Header file: config.h
// Last modified: 2023-12-06 18:21:19

namespace AoC
{
    namespace Metadata
    {
        static const char* version = "1.0.2023.1";
        static const char* author = "Marco Carosio";
        static const char* desc = "Advent of Code C++ repo";
        static const char* last_commit_date = "2023-12-06 18:20:55 +0100";
        static const char* last_commit_hash = "efd1061411d3c389047ccf91a080501a07f8f4f4";
    }

    namespace Settings
    {
        static const char *input_directory = "/home/marco/repos/github/mcarosio80/AoC2023/input";
    }
} // AoC

#endif // CONFIG_H
